### PR TITLE
6 sidebar controls and models

### PR DESCRIPTION
**Pull request by Cmdv**

### CODE REVIEW

**Comment by bitspook** [comment]
Remember I told you to pull new commits and base your further changs on them? 
We don't really need these changes actually. 

That is because the webpack changes that you added, `git rebase` took them back to past and replayed them on already present commits. So these changes are already there. Check this out: https://github.com/channikhabra/yarr/tree/6-sidebar-controls-and-models

Sorry I didn't clarify it properly earlier. I'd say pull new changes with `git pull origin master -f` and then checkout to tags to see the new state. Or just switch tags in github's UI and see what need to be changed. 

Playing with git history can be confusing (but the feeling of time-travel is worth every dime ;) ).

Sorry man you had to put so much work because I couldn't convey properly that our app is in new future because I took your webpack changes, went back in time, and put them in 0-setup step. So app's future got altered and every commit after 0-setup step has your webpack changes already. 

I'll close this PR without merging it, probably same for all other PRs you created today (after checking them of course).

**Comment by Cmdv** [comment]
Ah sorry total confusion all around!!! ignore today's PR's as all I was doing was adding Webpack. But the 0-5 I did readme checks.

I'll go read the link you've put learn what you actually meant haha

**Comment by bitspook** [comment]
When I said _it can be confusing_, I really meant it :) 

Let me try to explain what's really happening:

Before you made webpack changes, our git history looked like this:

0----1----2----3----4----5----6----7----8----9----10--X

Then you made webpack changes:

0----1----2----3----4----5----6----7----8----9----10----X----W (your fork)

Now we want `W` changes to be present in every step. So I created a new branch at `0`, and applied `W` to it.

0----1----2----3----4----5----6----7----8----9----10----X (my local repo)
\
 ---0W

And then I used `git rebase new-branch master` to apply `W` on every commit thereafter, and deleted new branch after that (and pushed changes to github):

0W----1W----2W----3W----4W----5W----6W----7W----8W----9W----10W----XW     (github version)

So at the end of the day, all the git history is changed (hence I call it a **new future** of the app), and your webpack changes are present.

I consciously chose this approach for this tutorial for relatively linear git history it produces (going frameworkless and using Rx weren't the only experiments I was trying in this tutorial :) )

One downside of this approach is that doing something in past creates a new history, so I have to manually move the tags to appropriate commits later.

The fact that `webpack.config.js` and `package.json` don't change throughout the tutorial after initial commit helps a lot (otherwise there'd be conflicts on every step of git rebase).

**Comment by Cmdv** [comment]
Ah cool, yeah there's a lot of information out there on rebase but they are mixed opinions and never really grasped it but your explanation has cleared things up. Really need to get better at git!!

**Pull request closed without merging**
