### PR TITLE
test

### PR DESCRIPTION
**Pull request by Cmdv**

### CODE REVIEW

**Comment by Cmdv** [comment]
sorry totally broken my git just had to run a test!! ignore

**Comment by bitspook** [comment]
lol Need some help?

---

Charanjit Singh
Github https://github.com/channikhabra || Twitter https://twitter.com/channikhabra || +91-7696166158

**Comment by Cmdv** [comment]
yeah trying to have it up to date with yours but it's not pulling in the history so I can't see the amends/new files on the tags :cry:

**Comment by bitspook** [comment]
You tried to force it?

`git pull origin master -f`

---

Charanjit Singh
Github https://github.com/channikhabra || Twitter https://twitter.com/channikhabra || +91-7696166158

**Comment by Cmdv** [comment]
well I was trying to `git merge upstream/master` but it is saying already up to date. just when I check on the tags the server.js isn't there!! git doesn't like me today!!

**Comment by bitspook** [comment]
Any reason you can't just delete that local repo of yours and clone from this github repo again?

**Comment by bitspook** [comment]
You can then add your fork's url as remote and force a push. It's brut-force, but it will do the job.

**Comment by Cmdv** [comment]
That is the issue my github repo isn't aligned to yours!

https://github.com/Cmdv/yarr/tree/5-fetch-feeds-and-styles

All the files we've updated are missing so I need to do some sort of a merge but in doing so it's all gone a little mental haha

**Comment by bitspook** [comment]
Try something from here: https://www.google.co.in/search?q=git+pull+rebased+branch&oq=git+pull+rebased&aqs=chrome.1.69i57j0l5.9654j0j7&sourceid=chrome&es_sm=91&ie=UTF-8

http://stackoverflow.com/questions/16773249/git-pulling-a-rebased-branch

I am trying too (I like playing with git)

**Comment by bitspook** [comment]
I got this one working. It creates a new commit at the end and all the commits before rebase which don't show up in the my repo's history show up in there, but it at least get you new commits. 
- `git fetch --all`
- `git checkout -b new_master channikhabra/master`
- `git branch -d master`
- `git branch -m new_master master`

I think it's basically the same thing as creating a new clone, minus the cleaner history. 

For a comparison, this is how the history of fresh clone of channikhabra/yarr look like:

screen shot 2015-08-02 at 8 18 59 pm

And this is how the history look like if you follow above steps:

screen shot 2015-08-02 at 8 20 08 pm

I'd say just create a new clone from channikhabra/yarr, add your fork's url as a remote, and make your changes on that. I am assuming you don't have pending commits, correct me if I am wrong.

**Comment by Cmdv** [comment]
Oh man I got so confused just wouldn't update or over write everything to reflect your github so I deleted my github and did a new branch!! I'm going to do some more github tutorials I think.

I started to use tower as it gave a good visual representation but I have a feeling its confusing things a little!! do you use any git programme with your terminal?

I'm going to start here it's about time I had fun with Github rather than have little struggles hehe.

Thanks again for the pointers it's really appreciated :smiley: 
I'll get on that webcast once I get the chance!

**Comment by bitspook** [comment]
I am not a fan of GUI tools, imo they just get in your way.

> do you use any git programme with your terminal?

You mean something other than git itself? No I don't.

Primarily I use Emacs and hence magit (git client in Emacs). Nothing can beat magit in terms of power and simplicity, for me magit is **the** git client 😛. Good thing about magit is that you need to know git to be able to use magit. Unlike the GUI tools which make things magical, magit take the magic out of your workflow while providing an unmatchable interface for git. 

> it's about time I had fun with Github

I assume you mean git :P Have fun :) All the time you invest in learning git is totally worth it.

**Pull request closed without merging**
