### PR TITLE
Typos and rewording up to start of Chapter 2

### PR DESCRIPTION
**Pull request by Cmdv**
Need to go through the rest of the tutorial but have made a start

### CODE REVIEW

**Comment by Cmdv** [comment]
Ah yeah cool I'm so used to using Webpack! I'll make that change, the rest is just wording really.

**Comment by bitspook** [comment]
Thanks for the keen eye and effort :)

**Comment by Cmdv** [comment]
ps: It will server up on `http://localhost:8080/` do you think it would be easier to put these commands in package.json?

**Comment by Cmdv** [comment]
not a problem very good tutorial =)

**Comment by bitspook** [comment]
@Cmdv yea it'll be better I think to have just `npm run` and `npm build` instead of webpack ones

**Comment by Cmdv** [comment]
Cool you want me to put them in or would you like to do it?

**Comment by bitspook** [comment]
I am doing some other work atm, so you can go ahead and create a pr. Please keep in mind to change the instructions as well. 

---

Charanjit Singh
Github https://github.com/channikhabra || Twitter https://twitter.com/channikhabra || +91-7696166158

**Comment by Cmdv** [comment]
yes not a problem will do

**Comment by Cmdv** [comment]
not sure if it's just me but I can't get the app to build!!

I just get this error in browser console `Uncaught Error: define cannot be used indirect` can't seem to work out what it is. have any ideas?

This is from cloning this repo and starting dev server + running build!

**Comment by bitspook** [comment]
Have you started using dexie.js? If yes, then you need to this hackish fix: https://github.com/channikhabra/yarr/blob/master/complete-tutorial.org#webpack-dexie-fixhack https://github.com/channikhabra/yarr/blob/master/complete-tutorial.org#webpack-dexie-fixhack

I checked on my system it’s building just fine.

---

Charanjit Singh
Github https://github.com/channikhabra || Twitter https://twitter.com/channikhabra || +91-7696166158

**Comment by Cmdv** [comment]
superb that fixed it, hadn't got that far was just trying to get a different way of getting webpack-dev-server to work so we could use `npm start / npm run build` then just go to `localhost:8080` and everything will work and hot reload from there. Not sure how that will work in the tutorial though. I'll make another pull request and you can let me know if it's worth implementing into the tutorial :smile:

**Comment by bitspook** [comment]
Cool. Enjoy yourself :)

---

Charanjit Singh
Github https://github.com/channikhabra || Twitter https://twitter.com/channikhabra || +91-7696166158

**Pull request merged**
